### ISSUE TITLE
실측 데이터 값이 다릅니다!

### ISSUE THREAD

**Issue by sunghwan2789** [AnkyoungMoo/StreetTree#11]
`SurveyActivity`에서 데이터가 올바르지 않게 보내지는 것 같은데 확인 부탁드려요.

* [x] 수목 번호를 `없음`으로 했는데 데이터 전송 시에는 null이 아니라 `공백 문자`로 보냄.
* [x] 받침틀을 `설치 전`으로 했는데 데이터 전송 시에는 `설치 후`로 보냄.
* [x] 첫 번째 실측에는 수목뿌리 사진을 찍고 두 번째 실측에는 `찍지 않았으나`,
  데이터 전송 시에는 `모두 사진을 찍은` 것으로 보냄(사진 정보 초기화 필요?).

```
MariaDB [mnlab]> select * from Measure \G
*************************** 1. row ***************************
            id: 1
 measureset_id: 1
sequenceNumber: 1
      latitude: 36.773708343506
     longitude: 126.93202209473
        siCode: 44
        guCode: 44200
      dongCode: 4420041000
     plateName: PLATE
    treeNumber: 52525252
   isInstalled: 0
        points: ["1","2","3","4"]
  rootImage_id: 1
*************************** 2. row ***************************
            id: 2
 measureset_id: 1
sequenceNumber: 2
      latitude: 36.775630950928
     longitude: 126.93364715576
        siCode: 44
        guCode: 44200
      dongCode: 4420041000
     plateName: PLATE
    treeNumber:
   isInstalled: 1
        points: ["23","3","3",null]
  rootImage_id: 1
2 rows in set (0.001 sec)
```
